### ISSUE TITLE
RuntimeError: Attempt to read ZIP archive that was already closed

### ISSUE THREAD

**Issue by ggayan** [CodeEffect/BoundKeys#2] opened 2013-05-17 15:07 UTC
Hi, first of all thanks for your plugin!

I've got the next error with it, this is my full sublimetext log:

startup, version: 3035 osx x64 channel: dev
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/mak/Library/Application Support/Sublime Text 3/Packages
state path: /Users/mak/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 8
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/mak/Library/Application Support/Sublime Text 3/Installed Packages
resources scanned
found 13 files for base name Default.sublime-keymap
found 2 files for base name Default.sublime-mousemap
found 9 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Flatland Dark.sublime-theme
theme loaded
app ready
pre session restore time: 0.144332
using gpu buffer for window
using gamma: 2 (err: 6.55744)
first paint time: 0.245288
wrote startup cache, added files: 1 orphaned files: 5 total files: 191 cache hits: 190
startup time: 0.290689
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Vintage.vintage
reloading plugin Vintage.vintage_commands
reloading plugin Vintage.vintage_motions
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin AlignTab.aligntab
reloading plugin ApplySyntax.ApplySyntax
reloading plugin ApplySyntax.is_rails_file
reloading plugin CoffeeScript.CoffeeScript
reloading plugin GitGutter.git_gutter
reloading plugin GitGutter.git_gutter_change
reloading plugin GitGutter.git_gutter_events
reloading plugin GitGutter.git_gutter_handler
reloading plugin GitGutter.git_helper
reloading plugin GitGutter.view_collection
reloading plugin SCSS.scss_completions
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.StatusBarFileSize
reloading plugin SideBarEnhancements.StatusBarModifiedTime
reloading plugin SublimeJEDI.python_go_to
reloading plugin SublimeJEDI.sublime_jedi
reloading plugin BoundKeys.boundkeys
reloading plugin FindSelected.findselected
reloading plugin Package Control.Package Control
loaded 1232 snippets
reloading plugin SideBarEnhancements.SideBarDefaultDisable
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2013-05-17 10:54:50, next run at 2013-05-17 11:54:50 or after
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "/Users/mak/Library/Application Support/Sublime Text 3/Packages/BoundKeys/boundkeys.py", line 300, in run
    str(zip.open(zipName, "r").read(), "utf-8")
  File "X/zipfile.py", line 1107, in open
RuntimeError: Attempt to read ZIP archive that was already closed

Any ideas?

**Comment by CodeEffect** [comment] 2013-05-17 19:04
Should be fixed by last commit, sloppy coding, if there were two keymap files in one of the sublime package zip files the zip file was closed after reading the first, before the second. 

Massive thanks for taking the time to report this, I picked up another issue whereby clashes weren't being picked up either, something I suspect I'd broken in a recent commit. Also, my first proper bug :YAY:

Please let me know if you still see issues after you update. 

EDIT: Be interested to confirm if that _was_ the cause for the bug if possible please. If it is you should see two table boxes as it were for one package. Likely one will be Default.sublime-keymap and the other will be Default (OSX).sublime-keymap. Cheers!

**Closed as completed** 2013-05-20 07:41 UTC
Labels: bug
